[tool.poetry]
name = "mediadownloaderPKG"
version = "0.1.0"
description = ""
authors = ["shift <fantasy_world4423-git@yahoo.co.jp>"]
license = "GNU Lesser General Public License v3.0"

[tool.poetry.dependencies]
beautifulsoup4 = "^4.10.0"
cryptography = "^36.0.1"
emoji = "^2.2.0"
isort = "^5.12.0"
mock = "^5.0.1"
numpy = "^1.24.2"
opencv-python = "^4.7.0.72"
pandas = "^1.5.3"
pillow = "^9.4.0"
PixivPy = "^3.6.2"
plyer = "^2.1.0"
pycodestyle = "^2.8.0"
pyppeteer = "^1.0.2"
PySimpleGUI = "^4.60.4"
python = ">=3.9,<4.0"
requests = "^2.28.2"
requests-html = "^0.10.0"

[tool.poetry.dev-dependencies]

[tool.isort]
multi_line_output = 9
line_length = 256

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
