[tool.poetry]
name = "mediadownloaderPKG"
version = "0.1.0"
description = ""
authors = ["shift <fantasy_world4423-git@yahoo.co.jp>"]
license = "GNU Lesser General Public License v3.0"

[tool.poetry.dependencies]
python = ">=3.9,<=3.10"
beautifulsoup4 = "^4.10.0"
cryptography = "^36.0.1"
emoji = "^1.6.3"
lxml = "^4.7.1"
mock = "^4.0.3"
numpy = "^1.22.1"
opencv-python = "^4.5.5"
pandas = "^1.3.5"
Pillow = "^9.0.0"
PixivPy = "^3.6.2"
pyppeteer = "^1.0.2"
PySimpleGUI = "^4.56.0"
pywin32 = "^303"
requests = "^2.27.1"
requests-html = "^0.10.0"
scipy = "^1.7.3"
setuptools = "^60.5.0"
six = "^1.16.0"
urllib3 = "^1.26.8"
pycodestyle = "^2.8.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
